name: main

on:
  push:
  pull_request:
    - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Lint
        uses: github/super-linter@v3.10.2